#!/bin/bash
# don't copy and paste my tool
# be gud one
# coded by adithziva
# colours 
#------------------------
a="\033[1;32m"
b="\033[1;31m"
c="\033[1;34m"
d="\033[0m"
e="\033[1;36m"
f="\033[1;37m"
g="\033[1;92m"
h="\033[1;93m"
i="\033[1;95m"
#-----------------------
trap 'printf "\n";stop;exit 1' 2
trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

user_interrupt(){
        printf "\e[0m\n"
        printf "\e[0m\e[1;36m\t CTRL + C Pressed \n"
        sleep 2
        banner
        printf "\e[0m\n"
        printf " \e[0m\e[1;42m Thanks for Using This Tool !!\e[0m\e[1;44m Visit https://github.com/adithziva\e[0m\n"
        printf "\e[0m\n"
        exit 1
}




banner() {
clear
figlet -f big '          BLVCK BOX' | lolcat
echo -e '\033[1m \e[32m                        your dream comes true'
printf "\e[0m\n"
printf "              \e[0m\e[1;100m LATEST TERMUX TOOL \e[0m  \e[1;42m [  BY : MR_ZIVA_  ] \e[0m\n"
printf "\e[0m\n"
}


choise() {
echo -e "                $a TO EXIT FROM THIS TOOL$b 'e'$a AND ENTER" 
echo -e "               $a TO INSTALL OTHER TOOL'S$b 'n'$a TO CONTINUE"
echo " "
read -p $'\e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' choice

if [ $choice = 'e' ] ; then
clear
banner
echo -e "                           $b SEE YOU LATER"
sleep 2
cd $HOME
elif [ $choice = 'n' ] ; then
clear
banner
menu
else
echo -e "                           $e invaild option"
sleep 1
echo -e "                              $e EXITING..."
fi
}

menu() {

printf "               \e[0m\e[1;32m[0] INSTALLED TOOLS WILL SHOW ON HOME [0]\e[0m\n"
printf "\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m01\e[0m\e[1;32m]\e[0m\e[1;31m Nexphisher  \e[0m\e[1;32m[\e[0m\e[1;77m11\e[0m\e[1;32m]\e[0m\e[1;93m Hydra       \e[0m\e[1;32m[\e[0m\e[1;77m21\e[0m\e[1;32m]\e[0m\e[1;31m M-WIZ       	\e[0m\e[1;32m[\e[0m\e[1;77m99\e[0m\e[1;32m]\e[0m\e[1;93m About\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m02\e[0m\e[1;32m]\e[0m\e[1;31m Infect      \e[0m\e[1;32m[\e[0m\e[1;77m12\e[0m\e[1;32m]\e[0m\e[1;93m Slowloris   \e[0m\e[1;32m[\e[0m\e[1;77m22\e[0m\e[1;32m]\e[0m\e[1;31m LAZYBEE		\e[0m\e[1;32m[\e[0m\e[1;77m00\e[0m\e[1;32m]\e[0m\e[1;93m Exit\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m03\e[0m\e[1;32m]\e[0m\e[1;31m Seeker      \e[0m\e[1;32m[\e[0m\e[1;77m13\e[0m\e[1;32m]\e[0m\e[1;93m IP Tracer   \e[0m\e[1;32m[\e[0m\e[1;77m23\e[0m\e[1;32m]\e[0m\e[1;31m MR PHISH\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m04\e[0m\e[1;32m]\e[0m\e[1;31m Ipdoner     \e[0m\e[1;32m[\e[0m\e[1;77m14\e[0m\e[1;32m]\e[0m\e[1;93m Easy-Hack   \e[0m\e[1;32m[\e[0m\e[1;77m24\e[0m\e[1;32m]\e[0m\e[1;31m DARKFLY\e[0m\n"	
printf " \e[1;32m[\e[0m\e[1;77m05\e[0m\e[1;32m]\e[0m\e[1;31m Zphisher    \e[0m\e[1;32m[\e[0m\e[1;77m15\e[0m\e[1;32m]\e[0m\e[1;93m CamPhish    \e[0m\e[1;32m[\e[0m\e[1;77m25\e[0m\e[1;32m]\e[0m\e[1;31m ONEX	\e[0m\n"	
printf " \e[1;32m[\e[0m\e[1;77m06\e[0m\e[1;32m]\e[0m\e[1;31m HackerPro   \e[0m\e[1;32m[\e[0m\e[1;77m16\e[0m\e[1;32m]\e[0m\e[1;93m Sayhello    \e[0m\e[1;32m[\e[0m\e[1;77m26\e[0m\e[1;32m]\e[0m\e[1;31m ADMINPANEL-F\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m07\e[0m\e[1;32m]\e[0m\e[1;31m Sqlmap      \e[0m\e[1;32m[\e[0m\e[1;77m17\e[0m\e[1;32m]\e[0m\e[1;93m Sigit       \e[0m\e[1;32m[\e[0m\e[1;77m27\e[0m\e[1;32m]\e[0m\e[1;31m T-LOAD\e[0m\n"		
printf " \e[1;32m[\e[0m\e[1;77m08\e[0m\e[1;32m]\e[0m\e[1;31m Nikto       \e[0m\e[1;32m[\e[0m\e[1;77m18\e[0m\e[1;32m]\e[0m\e[1;93m Insta-scrap \e[0m\e[1;32m[\e[0m\e[1;77m28\e[0m\e[1;32m]\e[0m\e[1;31m FOTOSPLOIT\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m09\e[0m\e[1;32m]\e[0m\e[1;31m Tool-x      \e[0m\e[1;32m[\e[0m\e[1;77m19\e[0m\e[1;32m]\e[0m\e[1;93m Osi.ig      \e[0m\e[1;32m[\e[0m\e[1;77m29\e[0m\e[1;32m]\e[0m\e[1;31m LAZYSCRIPT\e[0m\n"
printf " \e[1;32m[\e[0m\e[1;77m10\e[0m\e[1;32m]\e[0m\e[1;31m FSOCIETY    \e[0m\e[1;32m[\e[0m\e[1;77m20\e[0m\e[1;32m]\e[0m\e[1;93m Shark       \e[0m\e[1;32m[\e[0m\e[1;77m30\e[0m\e[1;32m]\e[0m\e[1;31m TERMUX-STYLE\e[0m\n"
printf "\e[0m\n"
read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' menu_option

if [[ $menu_option == 1 || $menu_option == 01 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING NEXPHISHHER \e[0m\n"
sleep 0.3
git clone https://github.com/htr-tech/nexphisher &>> start.log
rm start.log
printf "                    \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m NEXPHISHER WAS INSTALLED  \e[0m\n"
sleep 4 
banner
choise
elif [[ $menu_option == 2 || $menu_option == 02 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING INFECT \e[0m\n"
git clone https://github.com/noob-hackers/infect &>> start.log
rm start.log
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m INFECT WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 3 || $menu_option == 03 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SEEKER \e[0m\n"
git clone https://github.com/thewhiteh4t/seeker  &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SEEKER WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 4 || $menu_option == 04 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING IPDRONE \e[0m\n"
git clone https://github.com/noob-hackers/ipdrone &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m IPDRONE WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 5 || $menu_option == 05 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING ZPHISHER \e[0m\n"
git clone https://github.com/htr-tech/zphisher &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m ZPHISHER WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 6 || $menu_option == 06 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING HACKERPRO \e[0m\n"
git clone https://github.com/jaykali/hackerpro &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m HACKERPRO WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 7 || $menu_option == 07 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SQLMAP...\e[0m\n"
git clone https://github.com/sqlmapproject/sqlmap &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SQLMAP WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 8 || $menu_option == 08 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING NIKTO...\e[0m\n"
git clone https://github.com/sullo/nikto.git &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m NIKTO WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 9 || $menu_option == 09 ]]; then
cd -- &>> start.log
printf "                      \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING TOOL-X...\e[0m\n"
git clone https://github.com/Rajkumrdusad/Tool-X.git &>> start.log
rm start.log
sleep 0.2
printf "                     \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m TOOL-X WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 10 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING FSOCIETY...\e[0m\n"
git clone https://github.com/Manisso/fsociety.git &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m FSOCIETY WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 11 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING HYDRA...\e[0m\n"
git clone https://github.com/vanhauser-thc/thc-hydra &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m HYDRA WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 12 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SLOWLORIS...\e[0m\n"
git clone https://github.com/gkbrk/slowloris &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SLOWLORIS WAS INSTALLED  \e[0m\n"
sleep 4
banner                                                                                                    menu
choise
elif [[ $menu_option == 13 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING IP TRACER...\e[0m\n"
git clone https://github.com/rajkumardusad/IP-Tracer.git &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m IP TRACER WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 14 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING EASY-HACK...\e[0m\n"
git clone https://github.com/sabri-zaki/EasY_HaCk &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m EASY-HACK WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 15 ]]; then
cd -- &>> start.log
printf "                       \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING CAMPHISH...\e[0m\n"
git clone https://github.com/techchipnet/CamPhish &>> start.log
rm start.log
sleep 0.2
printf "                      \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m CAMPHISH WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 16 ]]; then
cd -- &>> start.log
printf "                        \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SAYHELLO...\e[0m\n"
git clone https://github.com/d093w1z/sayhello &>> start.log
rm start.log
sleep 0.2
printf "                       \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SAYHELLO WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 17 ]]; then
cd -- &>> start.log
printf "                         \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SIGIT...\e[0m\n"
git clone https://github.com/termuxhackers-id/SIGIT &>> start.log
rm start.log
sleep 0.2
printf "                       \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SIGIT WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 18 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING INSTA SCRAPER...\e[0m\n"
git clone https://github.com/arc298/instagram-scraper &>> start.log
rm start.log
sleep 0.2
printf "                       \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m INSTASCRAPER WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 19 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING OSI.IG...\e[0m\n"
git clone https://github.com/th3unkn0n/osi.ig &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m OSI.IG WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 20 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING SHARK...\e[0m\n"
git clone https://github.com/Bhaviktutorials/shark &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m SHARK WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 21 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING M-WIZ...\e[0m\n"
git clone https://github.com/noob-hackers/m-wiz &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m M-WIZ WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 22 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING LAZYBEE...\e[0m\n"
git clone https://github.com/noob-hackers/lazybee &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m LAZYBEE WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 23 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING MR PHISH...\e[0m\n"
git clone https://github.com/noob-hackers/mrphish &>> start.log 
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m MR PHISH WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 24 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING DARK FLY...\e[0m\n"
git clone https://github.com/Ranginang67/DarkFly-Tool &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m DARK FLY WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 25 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING ONEX...\e[0m\n"
git clone https://github.com/rajkumardusad/onex &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m ONEX WAS INSTALLED  \e[0m\n" 
sleep 4
banner
choise
elif [[ $menu_option == 26 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING ADMIN PANEL FINDER...\e[0m\n"
git clone https://github.com/alexhacker313/Admin-Panel-Finder &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m ADMIN PANEL FINDER WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 27 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING T-LOAD...  \e[0m\n"
git clone https://github.com/noob-hackers/T-LOAD &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m T-LOAD WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 28 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING FOTOSPLOIT...  \e[0m\n"
git clone https://github.com/Cesar-Hack-Gray/FotoSploit &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m FOTOSPLOIT WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 29 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING LAZYSCRIPT...  \e[0m\n"
git clone https://github.com/TechnicalMujeeb/Termux-Lazyscript &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m LAZYSCRIPT WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 30 ]]; then
cd -- &>> start.log
printf "                          \e[0m\e[1;35m [\e[1;97m~\e[1;35m]\e[1;93m CLONING TERMUX-STYLE...  \e[0m\n"
git clone https://github.com/adi1090x/termux-style &>> start.log
rm start.log
sleep 0.2
printf "                        \e[0m\e[1;32m [\e[1;97m~\e[1;32m]\e[1;93m TERMUX-STYLE WAS INSTALLED  \e[0m\n"
sleep 4
banner
choise
elif [[ $menu_option == 99 ]]; then
about
elif [[ $menu_option == 0 || $menu_option == 00 ]]; then
printf "\e[0m\n"
printf " \e[0m\e[1;42m Thanks for Using This Tool !!\e[0m\e[1;44m Visit https://github.com/adithziva\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf "\n\n \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
sleep 1
banner
menu
fi
}





about() {

clear
sleep 2
figlet -f  standard  '       BLVCK BOX' | lolcat
printf "\e[0m\e[1;100m Advanced tools for termux 30+ Tools\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[92m  AUTHOR \e[0m\e[91m     :\e[0m\e[93m BLVCK \e[0m\e[91m[\e[0m\e[93m mr_ziva_ \e[0m\e[91m]\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[92m  GITHUB \e[0m\e[91m     : \e[0m\e[96mhttps://github.com/adithziva\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[92m  Instagram \e[0m\e[91m  : \e[0m\e[96mhttps://instagram/mr_ziva_\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[92m  Version \e[0m\e[91m    : \e[0m\e[93m1.0\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[1;100m Follow Our Github For More Tools \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
sleep 3
printf " \e[0m\e[32m[\e[0m00\e[0m\e[32m]\e[0m\e[93m Home           \e[0m\e[32m[\e[0m99\e[0m\e[32m]\e[0m\e[93m Exit\e[0m\n"
printf "\e[0m\n"
read -p $' \e[1;32m[\e[0m\e[1;77m~\e[0m\e[1;32m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' about_option

if [[ $about_option == 0 || $about_option == 00 ]]; then
sleep 1
banner
menu
elif [[ $about_option == 99 ]]; then
sleep 1
banner
printf "\e[0m\n"
printf " \e[0m\e[1;42m Thanks for Using This Tool !!\e[0m  \e[1;44m Visit https://github.com/adithziva\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf "\n\n \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
sleep 1
banner
menu
fi
}


banner
menu
