#!/bin/bash
a="\033[1;32m"
b="\033[1;31m"
c="\033[1;34m"
w="\033[0m"
f="\033[1;36m"
g="\033[1;37m"
h="\033[1;92m"
i="\033[1;93m"
j="\033[1;95m"
echo -e $c"[~] "$b"STARTING INSTALLING PACKAGES"$c":"$i"WAIT 2 MIN"
sleep 1
pkg install gem &>> start.log
apt-get -y install figlet &>> start.log
gem install lolcat &>> start.log
clear
figlet -f  standard '                       BOX' | lolcat
printf "             \e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m BASIC PACKAGES [BY : MR_ZIVA_ ] \e[0m\n"
a="\033[1;32m"
b="\033[1;31m"
c="\033[1;34m"
w="\033[0m"
f="\033[1;36m"
g="\033[1;37m"
h="\033[1;92m"
i="\033[1;93m"
j="\033[1;95m"

sleep 0.2

echo -e $b"      +-+-+-+-+-+-+-+"$a"INSTALLING ALL PACKAGES"$b"+-+-+-+-+-+-+-+"
echo -e $a'              IT WILL TAKE 5MIN TO INSTALL ALL PACKAGES'
sleep 2

echo -e $c"> "$w"installing"$c":"$a"CURL"
apt-get -y install curl &>> start.log

echo -e $c"> "$w"installing"$c":"$f"NANO"
apt-get -y install nano &>> start.log

echo -e $c"> "$w"installing"$c":"$g"UPDATE"
apt-get -y install update &>> start.log

echo -e $c"> "$w"installing"$c":"$h"PYTHON"
apt-get -y install python &>> start.log

echo -e $c"> "$w"installing"$c":"$i"RUBY"
apt-get -y install ruby &>> start.log

echo -e $c"> "$w"installing"$c":"$j"FIGLET"
apt-get -y install figlet &>> start.log

echo -e $c"> "$w"installing"$c":"$e"PHP"
apt-get -y install php &>> start.log

echo -e $c"> "$w"installing"$c":"$f"OPENSSH"
apt-get -y install  openssh &>> start.log

echo -e $c"> "$w"installing"$c":"$g"REQUESTS"
pip3 install requests &>> start.log


apt-get -y install upgrade &>> start.log
apt-get -y install python3 python3-pip &>> start.log
apt-get -y install python2 &>> start.log
chmod +x blvckbox

printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !! \e[0m\n"
printf "\e[0m\n"
sleep 2
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Type \e[1;96mbash blvckbox \e[1;93mto run BLVCKBOX !! \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
